### ISSUE TITLE
Fails when too many files changed

### ISSUE THREAD

**Issue by danielrbradley** [reviewdog/action-actionlint#104]
We create PRs with quite a lot of files changes sometimes (> 10,000 files). This causes this action to fail with a message such as:

> reviewdog: post failed for actionlint: fail to parse diff: GET https://api.github.com/repos/pulumi/pulumi-azure-native/pulls/2553: 422 The diff could not be processed because too many files changed []

I'm not familiar with how this action works internally but might there be a way of adding an option to use a regular git checkout rather than attempting to fetch the diff via the API?

**Comment by javierjulio** [comment]
I don't believe this action does any diff fetch via an API. The expectation is that you are adding the checkout step in your workflow. This action doesn't perform it. Honestly, the best advice here is simply to not create large PRs as you would run into other errors anyway such as what we can post to GitHub PR checks.
