### ISSUE TITLE
Change the default filter_mode to file

### ISSUE THREAD

**Issue by massongit** [reviewdog/action-actionlint#130]
The default `filter_mode` of reviewdog/action-actionlint is `added`.
However, in the following cases, no error is displayed.
1. Assign a step id `test` to a `step`: https://github.com/massongit/action-actionlint/pull/1
2. Assign a step id `test` to a `step` before the `step` in step 1 in another PR: https://github.com/massongit/action-actionlint/pull/2
3. The following error occurs in the `step` in step 1. However, it is filtered because it is outside the range of PR diff in step 2.<br>https://github.com/rhysd/actionlint/blob/main/docs/checks.md#job-id-and-step-id-uniqueness

How about changing the default `filter_mode` to `file` so that the error is displayed in such cases?

**Comment by haya14busa** [comment]
+1 
 
Sounds good.
