### ISSUE TITLE
Create a `v1` branch that tracks the latest release

### ISSUE THREAD

**Issue by dgholz** [reviewdog/action-actionlint#17]
Hello, thanks for writing this action! Could you please create a `v1` branch that gets updated whenever you release/tag a new version? I've seen it recommended in https://docs.github.com/en/actions/creating-actions/about-actions#using-tags-for-release-management, and it would help me since I won't have to update all my workflows from `reviewdog/action-actionlint@v1.2.0` when you next publish a release.

Thanks!

edit: on closer reading, the docs I linked to recommend using a major version tag and moving it to point to the latest release. I feel like tags shouldn't be moved like that, only branches.

**Comment by shogo82148** [comment]
The `v1` tag is already here: https://github.com/reviewdog/action-actionlint/releases/tag/v1
So, you can use `reviewdog/action-actionlint@v1` in your workflows.

> I feel like tags shouldn't be moved like that, only branches.

I agree with you. I will re-think about it.

**Comment by javierjulio** [comment]
This is resolved by just scoping the action to the major version as how @shogo82148 has shared. Thank you.
