### ISSUE TITLE
UpdateCheckRun failed: Invalid request. Only 65535 characters are allowed

### ISSUE THREAD

**Issue by rocklan** [reviewdog/action-actionlint#72]
When I try to run this action I get this error:

```
{
   "severity":"ERROR",
   "time":"2022-06-14T04:04:49.473460382Z",
   "logging.googleapis.com/sourceLocation":{
      "file":"/home/runner/work/reviewdog/reviewdog/doghouse/server/github_checker.go",
      "line":"45",
      "function":"github.com/reviewdog/reviewdog/doghouse/server.(*checkerGitHubClient).UpdateCheckRun"
   },
   "message":"UpdateCheckRun failed: {\"message\":\"Invalid request.\\n\\nOnly 65535 characters are allowed; 95964 were supplied.\",\"documentation_url\":\"https://docs.github.com/rest/reference/checks#update-a-check-run\"}"
}
```

Perhaps my workflows have too many errors? :) Can the report be limited to 65535 characters?

**Comment by javierjulio** [comment]
@haya14busa I don't have access to close issues in this repo. Commenting here since I use this action often. This issue has been resolved by https://github.com/reviewdog/reviewdog/pull/1264 so it can be closed now. Thank you.

**Comment by haya14busa** [comment]
Thanks 💯
I also updated permission of this repo so that action-maintainer can maintain this repo.
